/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RegisterImport } from './routes/register'
import { Route as LoginImport } from './routes/login'
import { Route as LayoutImport } from './routes/_layout'
import { Route as LayoutIndexImport } from './routes/_layout/index'
import { Route as DashboardSetttingImport } from './routes/dashboard/settting'
import { Route as DashboardLayoutImport } from './routes/dashboard/_layout'
import { Route as LayoutCheckoutImport } from './routes/_layout/checkout'
import { Route as LayoutAboutImport } from './routes/_layout/about'
import { Route as DashboardLayoutIndexImport } from './routes/dashboard/_layout/index'
import { Route as DashboardLayoutProductsIndexImport } from './routes/dashboard/_layout/products/index'
import { Route as DashboardLayoutCategoryIndexImport } from './routes/dashboard/_layout/category/index'
import { Route as DashboardLayoutProductsCreateImport } from './routes/dashboard/_layout/products/create'
import { Route as DashboardLayoutCategoryCreateImport } from './routes/dashboard/_layout/category/create'
import { Route as DashboardLayoutProductsIdEditImport } from './routes/dashboard/_layout/products/$id.edit'
import { Route as DashboardLayoutCategoryIdEditImport } from './routes/dashboard/_layout/category/$id.edit'

// Create Virtual Routes

const DashboardImport = createFileRoute('/dashboard')()

// Create/Update Routes

const DashboardRoute = DashboardImport.update({
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const RegisterRoute = RegisterImport.update({
  path: '/register',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const DashboardSetttingRoute = DashboardSetttingImport.update({
  path: '/settting',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardLayoutRoute = DashboardLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => DashboardRoute,
} as any)

const LayoutCheckoutRoute = LayoutCheckoutImport.update({
  path: '/checkout',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutAboutRoute = LayoutAboutImport.update({
  path: '/about',
  getParentRoute: () => LayoutRoute,
} as any)

const DashboardLayoutIndexRoute = DashboardLayoutIndexImport.update({
  path: '/',
  getParentRoute: () => DashboardLayoutRoute,
} as any)

const DashboardLayoutProductsIndexRoute =
  DashboardLayoutProductsIndexImport.update({
    path: '/products/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

const DashboardLayoutCategoryIndexRoute =
  DashboardLayoutCategoryIndexImport.update({
    path: '/category/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

const DashboardLayoutProductsCreateRoute =
  DashboardLayoutProductsCreateImport.update({
    path: '/products/create',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

const DashboardLayoutCategoryCreateRoute =
  DashboardLayoutCategoryCreateImport.update({
    path: '/category/create',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

const DashboardLayoutProductsIdEditRoute =
  DashboardLayoutProductsIdEditImport.update({
    path: '/products/$id/edit',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

const DashboardLayoutCategoryIdEditRoute =
  DashboardLayoutCategoryIdEditImport.update({
    path: '/category/$id/edit',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterImport
      parentRoute: typeof rootRoute
    }
    '/_layout/about': {
      id: '/_layout/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof LayoutAboutImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/checkout': {
      id: '/_layout/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof LayoutCheckoutImport
      parentRoute: typeof LayoutImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/_layout': {
      id: '/dashboard/_layout'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardLayoutImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settting': {
      id: '/dashboard/settting'
      path: '/settting'
      fullPath: '/dashboard/settting'
      preLoaderRoute: typeof DashboardSetttingImport
      parentRoute: typeof DashboardImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
    '/dashboard/_layout/': {
      id: '/dashboard/_layout/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardLayoutIndexImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/dashboard/_layout/category/create': {
      id: '/dashboard/_layout/category/create'
      path: '/category/create'
      fullPath: '/dashboard/category/create'
      preLoaderRoute: typeof DashboardLayoutCategoryCreateImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/dashboard/_layout/products/create': {
      id: '/dashboard/_layout/products/create'
      path: '/products/create'
      fullPath: '/dashboard/products/create'
      preLoaderRoute: typeof DashboardLayoutProductsCreateImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/dashboard/_layout/category/': {
      id: '/dashboard/_layout/category/'
      path: '/category'
      fullPath: '/dashboard/category'
      preLoaderRoute: typeof DashboardLayoutCategoryIndexImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/dashboard/_layout/products/': {
      id: '/dashboard/_layout/products/'
      path: '/products'
      fullPath: '/dashboard/products'
      preLoaderRoute: typeof DashboardLayoutProductsIndexImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/dashboard/_layout/category/$id/edit': {
      id: '/dashboard/_layout/category/$id/edit'
      path: '/category/$id/edit'
      fullPath: '/dashboard/category/$id/edit'
      preLoaderRoute: typeof DashboardLayoutCategoryIdEditImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/dashboard/_layout/products/$id/edit': {
      id: '/dashboard/_layout/products/$id/edit'
      path: '/products/$id/edit'
      fullPath: '/dashboard/products/$id/edit'
      preLoaderRoute: typeof DashboardLayoutProductsIdEditImport
      parentRoute: typeof DashboardLayoutImport
    }
  }
}

// Create and export the route tree

interface LayoutRouteChildren {
  LayoutAboutRoute: typeof LayoutAboutRoute
  LayoutCheckoutRoute: typeof LayoutCheckoutRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAboutRoute: LayoutAboutRoute,
  LayoutCheckoutRoute: LayoutCheckoutRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

interface DashboardLayoutRouteChildren {
  DashboardLayoutIndexRoute: typeof DashboardLayoutIndexRoute
  DashboardLayoutCategoryCreateRoute: typeof DashboardLayoutCategoryCreateRoute
  DashboardLayoutProductsCreateRoute: typeof DashboardLayoutProductsCreateRoute
  DashboardLayoutCategoryIndexRoute: typeof DashboardLayoutCategoryIndexRoute
  DashboardLayoutProductsIndexRoute: typeof DashboardLayoutProductsIndexRoute
  DashboardLayoutCategoryIdEditRoute: typeof DashboardLayoutCategoryIdEditRoute
  DashboardLayoutProductsIdEditRoute: typeof DashboardLayoutProductsIdEditRoute
}

const DashboardLayoutRouteChildren: DashboardLayoutRouteChildren = {
  DashboardLayoutIndexRoute: DashboardLayoutIndexRoute,
  DashboardLayoutCategoryCreateRoute: DashboardLayoutCategoryCreateRoute,
  DashboardLayoutProductsCreateRoute: DashboardLayoutProductsCreateRoute,
  DashboardLayoutCategoryIndexRoute: DashboardLayoutCategoryIndexRoute,
  DashboardLayoutProductsIndexRoute: DashboardLayoutProductsIndexRoute,
  DashboardLayoutCategoryIdEditRoute: DashboardLayoutCategoryIdEditRoute,
  DashboardLayoutProductsIdEditRoute: DashboardLayoutProductsIdEditRoute,
}

const DashboardLayoutRouteWithChildren = DashboardLayoutRoute._addFileChildren(
  DashboardLayoutRouteChildren,
)

interface DashboardRouteChildren {
  DashboardLayoutRoute: typeof DashboardLayoutRouteWithChildren
  DashboardSetttingRoute: typeof DashboardSetttingRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardLayoutRoute: DashboardLayoutRouteWithChildren,
  DashboardSetttingRoute: DashboardSetttingRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/about': typeof LayoutAboutRoute
  '/checkout': typeof LayoutCheckoutRoute
  '/dashboard': typeof DashboardLayoutRouteWithChildren
  '/dashboard/settting': typeof DashboardSetttingRoute
  '/': typeof LayoutIndexRoute
  '/dashboard/': typeof DashboardLayoutIndexRoute
  '/dashboard/category/create': typeof DashboardLayoutCategoryCreateRoute
  '/dashboard/products/create': typeof DashboardLayoutProductsCreateRoute
  '/dashboard/category': typeof DashboardLayoutCategoryIndexRoute
  '/dashboard/products': typeof DashboardLayoutProductsIndexRoute
  '/dashboard/category/$id/edit': typeof DashboardLayoutCategoryIdEditRoute
  '/dashboard/products/$id/edit': typeof DashboardLayoutProductsIdEditRoute
}

export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/about': typeof LayoutAboutRoute
  '/checkout': typeof LayoutCheckoutRoute
  '/dashboard': typeof DashboardLayoutIndexRoute
  '/dashboard/settting': typeof DashboardSetttingRoute
  '/': typeof LayoutIndexRoute
  '/dashboard/category/create': typeof DashboardLayoutCategoryCreateRoute
  '/dashboard/products/create': typeof DashboardLayoutProductsCreateRoute
  '/dashboard/category': typeof DashboardLayoutCategoryIndexRoute
  '/dashboard/products': typeof DashboardLayoutProductsIndexRoute
  '/dashboard/category/$id/edit': typeof DashboardLayoutCategoryIdEditRoute
  '/dashboard/products/$id/edit': typeof DashboardLayoutProductsIdEditRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_layout/about': typeof LayoutAboutRoute
  '/_layout/checkout': typeof LayoutCheckoutRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/_layout': typeof DashboardLayoutRouteWithChildren
  '/dashboard/settting': typeof DashboardSetttingRoute
  '/_layout/': typeof LayoutIndexRoute
  '/dashboard/_layout/': typeof DashboardLayoutIndexRoute
  '/dashboard/_layout/category/create': typeof DashboardLayoutCategoryCreateRoute
  '/dashboard/_layout/products/create': typeof DashboardLayoutProductsCreateRoute
  '/dashboard/_layout/category/': typeof DashboardLayoutCategoryIndexRoute
  '/dashboard/_layout/products/': typeof DashboardLayoutProductsIndexRoute
  '/dashboard/_layout/category/$id/edit': typeof DashboardLayoutCategoryIdEditRoute
  '/dashboard/_layout/products/$id/edit': typeof DashboardLayoutProductsIdEditRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/login'
    | '/register'
    | '/about'
    | '/checkout'
    | '/dashboard'
    | '/dashboard/settting'
    | '/'
    | '/dashboard/'
    | '/dashboard/category/create'
    | '/dashboard/products/create'
    | '/dashboard/category'
    | '/dashboard/products'
    | '/dashboard/category/$id/edit'
    | '/dashboard/products/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | '/about'
    | '/checkout'
    | '/dashboard'
    | '/dashboard/settting'
    | '/'
    | '/dashboard/category/create'
    | '/dashboard/products/create'
    | '/dashboard/category'
    | '/dashboard/products'
    | '/dashboard/category/$id/edit'
    | '/dashboard/products/$id/edit'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/register'
    | '/_layout/about'
    | '/_layout/checkout'
    | '/dashboard'
    | '/dashboard/_layout'
    | '/dashboard/settting'
    | '/_layout/'
    | '/dashboard/_layout/'
    | '/dashboard/_layout/category/create'
    | '/dashboard/_layout/products/create'
    | '/dashboard/_layout/category/'
    | '/dashboard/_layout/products/'
    | '/dashboard/_layout/category/$id/edit'
    | '/dashboard/_layout/products/$id/edit'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  DashboardRoute: typeof DashboardRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  DashboardRoute: DashboardRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_layout",
        "/login",
        "/register",
        "/dashboard"
      ]
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/about",
        "/_layout/checkout",
        "/_layout/"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/register": {
      "filePath": "register.tsx"
    },
    "/_layout/about": {
      "filePath": "_layout/about.tsx",
      "parent": "/_layout"
    },
    "/_layout/checkout": {
      "filePath": "_layout/checkout.tsx",
      "parent": "/_layout"
    },
    "/dashboard": {
      "filePath": "dashboard",
      "children": [
        "/dashboard/_layout",
        "/dashboard/settting"
      ]
    },
    "/dashboard/_layout": {
      "filePath": "dashboard/_layout.tsx",
      "parent": "/dashboard",
      "children": [
        "/dashboard/_layout/",
        "/dashboard/_layout/category/create",
        "/dashboard/_layout/products/create",
        "/dashboard/_layout/category/",
        "/dashboard/_layout/products/",
        "/dashboard/_layout/category/$id/edit",
        "/dashboard/_layout/products/$id/edit"
      ]
    },
    "/dashboard/settting": {
      "filePath": "dashboard/settting.tsx",
      "parent": "/dashboard"
    },
    "/_layout/": {
      "filePath": "_layout/index.tsx",
      "parent": "/_layout"
    },
    "/dashboard/_layout/": {
      "filePath": "dashboard/_layout/index.tsx",
      "parent": "/dashboard/_layout"
    },
    "/dashboard/_layout/category/create": {
      "filePath": "dashboard/_layout/category/create.tsx",
      "parent": "/dashboard/_layout"
    },
    "/dashboard/_layout/products/create": {
      "filePath": "dashboard/_layout/products/create.tsx",
      "parent": "/dashboard/_layout"
    },
    "/dashboard/_layout/category/": {
      "filePath": "dashboard/_layout/category/index.tsx",
      "parent": "/dashboard/_layout"
    },
    "/dashboard/_layout/products/": {
      "filePath": "dashboard/_layout/products/index.tsx",
      "parent": "/dashboard/_layout"
    },
    "/dashboard/_layout/category/$id/edit": {
      "filePath": "dashboard/_layout/category/$id.edit.tsx",
      "parent": "/dashboard/_layout"
    },
    "/dashboard/_layout/products/$id/edit": {
      "filePath": "dashboard/_layout/products/$id.edit.tsx",
      "parent": "/dashboard/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
