/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TokenExpiresImport } from './routes/token-expires'
import { Route as ResetPasswordImport } from './routes/reset-password'
import { Route as RegisterImport } from './routes/register'
import { Route as LoginImport } from './routes/login'
import { Route as ForgotPasswordImport } from './routes/forgot-password'
import { Route as LayoutImport } from './routes/_layout'
import { Route as LayoutIndexImport } from './routes/_layout/index'
import { Route as DashboardSetttingImport } from './routes/dashboard/settting'
import { Route as DashboardLayoutImport } from './routes/dashboard/_layout'
import { Route as LayoutThanksImport } from './routes/_layout/thanks'
import { Route as LayoutShopImport } from './routes/_layout/shop'
import { Route as LayoutOrderuserImport } from './routes/_layout/orderuser'
import { Route as LayoutCheckoutImport } from './routes/_layout/checkout'
import { Route as LayoutCartImport } from './routes/_layout/cart'
import { Route as LayoutAboutImport } from './routes/_layout/about'
import { Route as DashboardLayoutIndexImport } from './routes/dashboard/_layout/index'
import { Route as LayoutSlugQuickviewProductImport } from './routes/_layout/$slug.quickviewProduct'
import { Route as LayoutSlugDetailproductImport } from './routes/_layout/$slug.detailproduct'
import { Route as DashboardLayoutUsersIndexImport } from './routes/dashboard/_layout/users/index'
import { Route as DashboardLayoutProductsIndexImport } from './routes/dashboard/_layout/products/index'
import { Route as DashboardLayoutOrderIndexImport } from './routes/dashboard/_layout/order/index'
import { Route as DashboardLayoutCouponIndexImport } from './routes/dashboard/_layout/coupon/index'
import { Route as DashboardLayoutCategoryIndexImport } from './routes/dashboard/_layout/category/index'
import { Route as DashboardLayoutProductsCreateImport } from './routes/dashboard/_layout/products/create'
import { Route as DashboardLayoutCouponCreateImport } from './routes/dashboard/_layout/coupon/create'
import { Route as DashboardLayoutCategoryCreateImport } from './routes/dashboard/_layout/category/create'
import { Route as LayoutReturnUserIdOrderIdImport } from './routes/_layout/return.$userId.$orderId'
import { Route as DashboardLayoutProductsIdEditImport } from './routes/dashboard/_layout/products/$id.edit'
import { Route as DashboardLayoutCouponIdEditImport } from './routes/dashboard/_layout/coupon/$id.edit'
import { Route as DashboardLayoutCategoryIdEditImport } from './routes/dashboard/_layout/category/$id.edit'

// Create Virtual Routes

const DashboardImport = createFileRoute('/dashboard')()

// Create/Update Routes

const DashboardRoute = DashboardImport.update({
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const TokenExpiresRoute = TokenExpiresImport.update({
  path: '/token-expires',
  getParentRoute: () => rootRoute,
} as any)

const ResetPasswordRoute = ResetPasswordImport.update({
  path: '/reset-password',
  getParentRoute: () => rootRoute,
} as any)

const RegisterRoute = RegisterImport.update({
  path: '/register',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const ForgotPasswordRoute = ForgotPasswordImport.update({
  path: '/forgot-password',
  getParentRoute: () => rootRoute,
} as any)

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const DashboardSetttingRoute = DashboardSetttingImport.update({
  path: '/settting',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardLayoutRoute = DashboardLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => DashboardRoute,
} as any)

const LayoutThanksRoute = LayoutThanksImport.update({
  path: '/thanks',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutShopRoute = LayoutShopImport.update({
  path: '/shop',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutOrderuserRoute = LayoutOrderuserImport.update({
  path: '/orderuser',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutCheckoutRoute = LayoutCheckoutImport.update({
  path: '/checkout',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutCartRoute = LayoutCartImport.update({
  path: '/cart',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutAboutRoute = LayoutAboutImport.update({
  path: '/about',
  getParentRoute: () => LayoutRoute,
} as any)

const DashboardLayoutIndexRoute = DashboardLayoutIndexImport.update({
  path: '/',
  getParentRoute: () => DashboardLayoutRoute,
} as any)

const LayoutSlugQuickviewProductRoute = LayoutSlugQuickviewProductImport.update(
  {
    path: '/$slug/quickviewProduct',
    getParentRoute: () => LayoutRoute,
  } as any,
)

const LayoutSlugDetailproductRoute = LayoutSlugDetailproductImport.update({
  path: '/$slug/detailproduct',
  getParentRoute: () => LayoutRoute,
} as any)

const DashboardLayoutUsersIndexRoute = DashboardLayoutUsersIndexImport.update({
  path: '/users/',
  getParentRoute: () => DashboardLayoutRoute,
} as any)

const DashboardLayoutProductsIndexRoute =
  DashboardLayoutProductsIndexImport.update({
    path: '/products/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

const DashboardLayoutOrderIndexRoute = DashboardLayoutOrderIndexImport.update({
  path: '/order/',
  getParentRoute: () => DashboardLayoutRoute,
} as any)

const DashboardLayoutCouponIndexRoute = DashboardLayoutCouponIndexImport.update(
  {
    path: '/coupon/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any,
)

const DashboardLayoutCategoryIndexRoute =
  DashboardLayoutCategoryIndexImport.update({
    path: '/category/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

const DashboardLayoutProductsCreateRoute =
  DashboardLayoutProductsCreateImport.update({
    path: '/products/create',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

const DashboardLayoutCouponCreateRoute =
  DashboardLayoutCouponCreateImport.update({
    path: '/coupon/create',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

const DashboardLayoutCategoryCreateRoute =
  DashboardLayoutCategoryCreateImport.update({
    path: '/category/create',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

const LayoutReturnUserIdOrderIdRoute = LayoutReturnUserIdOrderIdImport.update({
  path: '/return/$userId/$orderId',
  getParentRoute: () => LayoutRoute,
} as any)

const DashboardLayoutProductsIdEditRoute =
  DashboardLayoutProductsIdEditImport.update({
    path: '/products/$id/edit',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

const DashboardLayoutCouponIdEditRoute =
  DashboardLayoutCouponIdEditImport.update({
    path: '/coupon/$id/edit',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

const DashboardLayoutCategoryIdEditRoute =
  DashboardLayoutCategoryIdEditImport.update({
    path: '/category/$id/edit',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterImport
      parentRoute: typeof rootRoute
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordImport
      parentRoute: typeof rootRoute
    }
    '/token-expires': {
      id: '/token-expires'
      path: '/token-expires'
      fullPath: '/token-expires'
      preLoaderRoute: typeof TokenExpiresImport
      parentRoute: typeof rootRoute
    }
    '/_layout/about': {
      id: '/_layout/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof LayoutAboutImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/cart': {
      id: '/_layout/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof LayoutCartImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/checkout': {
      id: '/_layout/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof LayoutCheckoutImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/orderuser': {
      id: '/_layout/orderuser'
      path: '/orderuser'
      fullPath: '/orderuser'
      preLoaderRoute: typeof LayoutOrderuserImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/shop': {
      id: '/_layout/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof LayoutShopImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/thanks': {
      id: '/_layout/thanks'
      path: '/thanks'
      fullPath: '/thanks'
      preLoaderRoute: typeof LayoutThanksImport
      parentRoute: typeof LayoutImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/_layout': {
      id: '/dashboard/_layout'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardLayoutImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settting': {
      id: '/dashboard/settting'
      path: '/settting'
      fullPath: '/dashboard/settting'
      preLoaderRoute: typeof DashboardSetttingImport
      parentRoute: typeof DashboardImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/$slug/detailproduct': {
      id: '/_layout/$slug/detailproduct'
      path: '/$slug/detailproduct'
      fullPath: '/$slug/detailproduct'
      preLoaderRoute: typeof LayoutSlugDetailproductImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/$slug/quickviewProduct': {
      id: '/_layout/$slug/quickviewProduct'
      path: '/$slug/quickviewProduct'
      fullPath: '/$slug/quickviewProduct'
      preLoaderRoute: typeof LayoutSlugQuickviewProductImport
      parentRoute: typeof LayoutImport
    }
    '/dashboard/_layout/': {
      id: '/dashboard/_layout/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardLayoutIndexImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/_layout/return/$userId/$orderId': {
      id: '/_layout/return/$userId/$orderId'
      path: '/return/$userId/$orderId'
      fullPath: '/return/$userId/$orderId'
      preLoaderRoute: typeof LayoutReturnUserIdOrderIdImport
      parentRoute: typeof LayoutImport
    }
    '/dashboard/_layout/category/create': {
      id: '/dashboard/_layout/category/create'
      path: '/category/create'
      fullPath: '/dashboard/category/create'
      preLoaderRoute: typeof DashboardLayoutCategoryCreateImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/dashboard/_layout/coupon/create': {
      id: '/dashboard/_layout/coupon/create'
      path: '/coupon/create'
      fullPath: '/dashboard/coupon/create'
      preLoaderRoute: typeof DashboardLayoutCouponCreateImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/dashboard/_layout/products/create': {
      id: '/dashboard/_layout/products/create'
      path: '/products/create'
      fullPath: '/dashboard/products/create'
      preLoaderRoute: typeof DashboardLayoutProductsCreateImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/dashboard/_layout/category/': {
      id: '/dashboard/_layout/category/'
      path: '/category'
      fullPath: '/dashboard/category'
      preLoaderRoute: typeof DashboardLayoutCategoryIndexImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/dashboard/_layout/coupon/': {
      id: '/dashboard/_layout/coupon/'
      path: '/coupon'
      fullPath: '/dashboard/coupon'
      preLoaderRoute: typeof DashboardLayoutCouponIndexImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/dashboard/_layout/order/': {
      id: '/dashboard/_layout/order/'
      path: '/order'
      fullPath: '/dashboard/order'
      preLoaderRoute: typeof DashboardLayoutOrderIndexImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/dashboard/_layout/products/': {
      id: '/dashboard/_layout/products/'
      path: '/products'
      fullPath: '/dashboard/products'
      preLoaderRoute: typeof DashboardLayoutProductsIndexImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/dashboard/_layout/users/': {
      id: '/dashboard/_layout/users/'
      path: '/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof DashboardLayoutUsersIndexImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/dashboard/_layout/category/$id/edit': {
      id: '/dashboard/_layout/category/$id/edit'
      path: '/category/$id/edit'
      fullPath: '/dashboard/category/$id/edit'
      preLoaderRoute: typeof DashboardLayoutCategoryIdEditImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/dashboard/_layout/coupon/$id/edit': {
      id: '/dashboard/_layout/coupon/$id/edit'
      path: '/coupon/$id/edit'
      fullPath: '/dashboard/coupon/$id/edit'
      preLoaderRoute: typeof DashboardLayoutCouponIdEditImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/dashboard/_layout/products/$id/edit': {
      id: '/dashboard/_layout/products/$id/edit'
      path: '/products/$id/edit'
      fullPath: '/dashboard/products/$id/edit'
      preLoaderRoute: typeof DashboardLayoutProductsIdEditImport
      parentRoute: typeof DashboardLayoutImport
    }
  }
}

// Create and export the route tree

interface LayoutRouteChildren {
  LayoutAboutRoute: typeof LayoutAboutRoute
  LayoutCartRoute: typeof LayoutCartRoute
  LayoutCheckoutRoute: typeof LayoutCheckoutRoute
  LayoutOrderuserRoute: typeof LayoutOrderuserRoute
  LayoutShopRoute: typeof LayoutShopRoute
  LayoutThanksRoute: typeof LayoutThanksRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutSlugDetailproductRoute: typeof LayoutSlugDetailproductRoute
  LayoutSlugQuickviewProductRoute: typeof LayoutSlugQuickviewProductRoute
  LayoutReturnUserIdOrderIdRoute: typeof LayoutReturnUserIdOrderIdRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAboutRoute: LayoutAboutRoute,
  LayoutCartRoute: LayoutCartRoute,
  LayoutCheckoutRoute: LayoutCheckoutRoute,
  LayoutOrderuserRoute: LayoutOrderuserRoute,
  LayoutShopRoute: LayoutShopRoute,
  LayoutThanksRoute: LayoutThanksRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutSlugDetailproductRoute: LayoutSlugDetailproductRoute,
  LayoutSlugQuickviewProductRoute: LayoutSlugQuickviewProductRoute,
  LayoutReturnUserIdOrderIdRoute: LayoutReturnUserIdOrderIdRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

interface DashboardLayoutRouteChildren {
  DashboardLayoutIndexRoute: typeof DashboardLayoutIndexRoute
  DashboardLayoutCategoryCreateRoute: typeof DashboardLayoutCategoryCreateRoute
  DashboardLayoutCouponCreateRoute: typeof DashboardLayoutCouponCreateRoute
  DashboardLayoutProductsCreateRoute: typeof DashboardLayoutProductsCreateRoute
  DashboardLayoutCategoryIndexRoute: typeof DashboardLayoutCategoryIndexRoute
  DashboardLayoutCouponIndexRoute: typeof DashboardLayoutCouponIndexRoute
  DashboardLayoutOrderIndexRoute: typeof DashboardLayoutOrderIndexRoute
  DashboardLayoutProductsIndexRoute: typeof DashboardLayoutProductsIndexRoute
  DashboardLayoutUsersIndexRoute: typeof DashboardLayoutUsersIndexRoute
  DashboardLayoutCategoryIdEditRoute: typeof DashboardLayoutCategoryIdEditRoute
  DashboardLayoutCouponIdEditRoute: typeof DashboardLayoutCouponIdEditRoute
  DashboardLayoutProductsIdEditRoute: typeof DashboardLayoutProductsIdEditRoute
}

const DashboardLayoutRouteChildren: DashboardLayoutRouteChildren = {
  DashboardLayoutIndexRoute: DashboardLayoutIndexRoute,
  DashboardLayoutCategoryCreateRoute: DashboardLayoutCategoryCreateRoute,
  DashboardLayoutCouponCreateRoute: DashboardLayoutCouponCreateRoute,
  DashboardLayoutProductsCreateRoute: DashboardLayoutProductsCreateRoute,
  DashboardLayoutCategoryIndexRoute: DashboardLayoutCategoryIndexRoute,
  DashboardLayoutCouponIndexRoute: DashboardLayoutCouponIndexRoute,
  DashboardLayoutOrderIndexRoute: DashboardLayoutOrderIndexRoute,
  DashboardLayoutProductsIndexRoute: DashboardLayoutProductsIndexRoute,
  DashboardLayoutUsersIndexRoute: DashboardLayoutUsersIndexRoute,
  DashboardLayoutCategoryIdEditRoute: DashboardLayoutCategoryIdEditRoute,
  DashboardLayoutCouponIdEditRoute: DashboardLayoutCouponIdEditRoute,
  DashboardLayoutProductsIdEditRoute: DashboardLayoutProductsIdEditRoute,
}

const DashboardLayoutRouteWithChildren = DashboardLayoutRoute._addFileChildren(
  DashboardLayoutRouteChildren,
)

interface DashboardRouteChildren {
  DashboardLayoutRoute: typeof DashboardLayoutRouteWithChildren
  DashboardSetttingRoute: typeof DashboardSetttingRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardLayoutRoute: DashboardLayoutRouteWithChildren,
  DashboardSetttingRoute: DashboardSetttingRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof LayoutRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/token-expires': typeof TokenExpiresRoute
  '/about': typeof LayoutAboutRoute
  '/cart': typeof LayoutCartRoute
  '/checkout': typeof LayoutCheckoutRoute
  '/orderuser': typeof LayoutOrderuserRoute
  '/shop': typeof LayoutShopRoute
  '/thanks': typeof LayoutThanksRoute
  '/dashboard': typeof DashboardLayoutRouteWithChildren
  '/dashboard/settting': typeof DashboardSetttingRoute
  '/': typeof LayoutIndexRoute
  '/$slug/detailproduct': typeof LayoutSlugDetailproductRoute
  '/$slug/quickviewProduct': typeof LayoutSlugQuickviewProductRoute
  '/dashboard/': typeof DashboardLayoutIndexRoute
  '/return/$userId/$orderId': typeof LayoutReturnUserIdOrderIdRoute
  '/dashboard/category/create': typeof DashboardLayoutCategoryCreateRoute
  '/dashboard/coupon/create': typeof DashboardLayoutCouponCreateRoute
  '/dashboard/products/create': typeof DashboardLayoutProductsCreateRoute
  '/dashboard/category': typeof DashboardLayoutCategoryIndexRoute
  '/dashboard/coupon': typeof DashboardLayoutCouponIndexRoute
  '/dashboard/order': typeof DashboardLayoutOrderIndexRoute
  '/dashboard/products': typeof DashboardLayoutProductsIndexRoute
  '/dashboard/users': typeof DashboardLayoutUsersIndexRoute
  '/dashboard/category/$id/edit': typeof DashboardLayoutCategoryIdEditRoute
  '/dashboard/coupon/$id/edit': typeof DashboardLayoutCouponIdEditRoute
  '/dashboard/products/$id/edit': typeof DashboardLayoutProductsIdEditRoute
}

export interface FileRoutesByTo {
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/token-expires': typeof TokenExpiresRoute
  '/about': typeof LayoutAboutRoute
  '/cart': typeof LayoutCartRoute
  '/checkout': typeof LayoutCheckoutRoute
  '/orderuser': typeof LayoutOrderuserRoute
  '/shop': typeof LayoutShopRoute
  '/thanks': typeof LayoutThanksRoute
  '/dashboard': typeof DashboardLayoutIndexRoute
  '/dashboard/settting': typeof DashboardSetttingRoute
  '/': typeof LayoutIndexRoute
  '/$slug/detailproduct': typeof LayoutSlugDetailproductRoute
  '/$slug/quickviewProduct': typeof LayoutSlugQuickviewProductRoute
  '/return/$userId/$orderId': typeof LayoutReturnUserIdOrderIdRoute
  '/dashboard/category/create': typeof DashboardLayoutCategoryCreateRoute
  '/dashboard/coupon/create': typeof DashboardLayoutCouponCreateRoute
  '/dashboard/products/create': typeof DashboardLayoutProductsCreateRoute
  '/dashboard/category': typeof DashboardLayoutCategoryIndexRoute
  '/dashboard/coupon': typeof DashboardLayoutCouponIndexRoute
  '/dashboard/order': typeof DashboardLayoutOrderIndexRoute
  '/dashboard/products': typeof DashboardLayoutProductsIndexRoute
  '/dashboard/users': typeof DashboardLayoutUsersIndexRoute
  '/dashboard/category/$id/edit': typeof DashboardLayoutCategoryIdEditRoute
  '/dashboard/coupon/$id/edit': typeof DashboardLayoutCouponIdEditRoute
  '/dashboard/products/$id/edit': typeof DashboardLayoutProductsIdEditRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/token-expires': typeof TokenExpiresRoute
  '/_layout/about': typeof LayoutAboutRoute
  '/_layout/cart': typeof LayoutCartRoute
  '/_layout/checkout': typeof LayoutCheckoutRoute
  '/_layout/orderuser': typeof LayoutOrderuserRoute
  '/_layout/shop': typeof LayoutShopRoute
  '/_layout/thanks': typeof LayoutThanksRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/_layout': typeof DashboardLayoutRouteWithChildren
  '/dashboard/settting': typeof DashboardSetttingRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/$slug/detailproduct': typeof LayoutSlugDetailproductRoute
  '/_layout/$slug/quickviewProduct': typeof LayoutSlugQuickviewProductRoute
  '/dashboard/_layout/': typeof DashboardLayoutIndexRoute
  '/_layout/return/$userId/$orderId': typeof LayoutReturnUserIdOrderIdRoute
  '/dashboard/_layout/category/create': typeof DashboardLayoutCategoryCreateRoute
  '/dashboard/_layout/coupon/create': typeof DashboardLayoutCouponCreateRoute
  '/dashboard/_layout/products/create': typeof DashboardLayoutProductsCreateRoute
  '/dashboard/_layout/category/': typeof DashboardLayoutCategoryIndexRoute
  '/dashboard/_layout/coupon/': typeof DashboardLayoutCouponIndexRoute
  '/dashboard/_layout/order/': typeof DashboardLayoutOrderIndexRoute
  '/dashboard/_layout/products/': typeof DashboardLayoutProductsIndexRoute
  '/dashboard/_layout/users/': typeof DashboardLayoutUsersIndexRoute
  '/dashboard/_layout/category/$id/edit': typeof DashboardLayoutCategoryIdEditRoute
  '/dashboard/_layout/coupon/$id/edit': typeof DashboardLayoutCouponIdEditRoute
  '/dashboard/_layout/products/$id/edit': typeof DashboardLayoutProductsIdEditRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/token-expires'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/orderuser'
    | '/shop'
    | '/thanks'
    | '/dashboard'
    | '/dashboard/settting'
    | '/'
    | '/$slug/detailproduct'
    | '/$slug/quickviewProduct'
    | '/dashboard/'
    | '/return/$userId/$orderId'
    | '/dashboard/category/create'
    | '/dashboard/coupon/create'
    | '/dashboard/products/create'
    | '/dashboard/category'
    | '/dashboard/coupon'
    | '/dashboard/order'
    | '/dashboard/products'
    | '/dashboard/users'
    | '/dashboard/category/$id/edit'
    | '/dashboard/coupon/$id/edit'
    | '/dashboard/products/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/token-expires'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/orderuser'
    | '/shop'
    | '/thanks'
    | '/dashboard'
    | '/dashboard/settting'
    | '/'
    | '/$slug/detailproduct'
    | '/$slug/quickviewProduct'
    | '/return/$userId/$orderId'
    | '/dashboard/category/create'
    | '/dashboard/coupon/create'
    | '/dashboard/products/create'
    | '/dashboard/category'
    | '/dashboard/coupon'
    | '/dashboard/order'
    | '/dashboard/products'
    | '/dashboard/users'
    | '/dashboard/category/$id/edit'
    | '/dashboard/coupon/$id/edit'
    | '/dashboard/products/$id/edit'
  id:
    | '__root__'
    | '/_layout'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/token-expires'
    | '/_layout/about'
    | '/_layout/cart'
    | '/_layout/checkout'
    | '/_layout/orderuser'
    | '/_layout/shop'
    | '/_layout/thanks'
    | '/dashboard'
    | '/dashboard/_layout'
    | '/dashboard/settting'
    | '/_layout/'
    | '/_layout/$slug/detailproduct'
    | '/_layout/$slug/quickviewProduct'
    | '/dashboard/_layout/'
    | '/_layout/return/$userId/$orderId'
    | '/dashboard/_layout/category/create'
    | '/dashboard/_layout/coupon/create'
    | '/dashboard/_layout/products/create'
    | '/dashboard/_layout/category/'
    | '/dashboard/_layout/coupon/'
    | '/dashboard/_layout/order/'
    | '/dashboard/_layout/products/'
    | '/dashboard/_layout/users/'
    | '/dashboard/_layout/category/$id/edit'
    | '/dashboard/_layout/coupon/$id/edit'
    | '/dashboard/_layout/products/$id/edit'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TokenExpiresRoute: typeof TokenExpiresRoute
  DashboardRoute: typeof DashboardRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TokenExpiresRoute: TokenExpiresRoute,
  DashboardRoute: DashboardRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_layout",
        "/forgot-password",
        "/login",
        "/register",
        "/reset-password",
        "/token-expires",
        "/dashboard"
      ]
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/about",
        "/_layout/cart",
        "/_layout/checkout",
        "/_layout/orderuser",
        "/_layout/shop",
        "/_layout/thanks",
        "/_layout/",
        "/_layout/$slug/detailproduct",
        "/_layout/$slug/quickviewProduct",
        "/_layout/return/$userId/$orderId"
      ]
    },
    "/forgot-password": {
      "filePath": "forgot-password.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/register": {
      "filePath": "register.tsx"
    },
    "/reset-password": {
      "filePath": "reset-password.tsx"
    },
    "/token-expires": {
      "filePath": "token-expires.tsx"
    },
    "/_layout/about": {
      "filePath": "_layout/about.tsx",
      "parent": "/_layout"
    },
    "/_layout/cart": {
      "filePath": "_layout/cart.tsx",
      "parent": "/_layout"
    },
    "/_layout/checkout": {
      "filePath": "_layout/checkout.tsx",
      "parent": "/_layout"
    },
    "/_layout/orderuser": {
      "filePath": "_layout/orderuser.tsx",
      "parent": "/_layout"
    },
    "/_layout/shop": {
      "filePath": "_layout/shop.tsx",
      "parent": "/_layout"
    },
    "/_layout/thanks": {
      "filePath": "_layout/thanks.tsx",
      "parent": "/_layout"
    },
    "/dashboard": {
      "filePath": "dashboard",
      "children": [
        "/dashboard/_layout",
        "/dashboard/settting"
      ]
    },
    "/dashboard/_layout": {
      "filePath": "dashboard/_layout.tsx",
      "parent": "/dashboard",
      "children": [
        "/dashboard/_layout/",
        "/dashboard/_layout/category/create",
        "/dashboard/_layout/coupon/create",
        "/dashboard/_layout/products/create",
        "/dashboard/_layout/category/",
        "/dashboard/_layout/coupon/",
        "/dashboard/_layout/order/",
        "/dashboard/_layout/products/",
        "/dashboard/_layout/users/",
        "/dashboard/_layout/category/$id/edit",
        "/dashboard/_layout/coupon/$id/edit",
        "/dashboard/_layout/products/$id/edit"
      ]
    },
    "/dashboard/settting": {
      "filePath": "dashboard/settting.tsx",
      "parent": "/dashboard"
    },
    "/_layout/": {
      "filePath": "_layout/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/$slug/detailproduct": {
      "filePath": "_layout/$slug.detailproduct.tsx",
      "parent": "/_layout"
    },
    "/_layout/$slug/quickviewProduct": {
      "filePath": "_layout/$slug.quickviewProduct.tsx",
      "parent": "/_layout"
    },
    "/dashboard/_layout/": {
      "filePath": "dashboard/_layout/index.tsx",
      "parent": "/dashboard/_layout"
    },
    "/_layout/return/$userId/$orderId": {
      "filePath": "_layout/return.$userId.$orderId.tsx",
      "parent": "/_layout"
    },
    "/dashboard/_layout/category/create": {
      "filePath": "dashboard/_layout/category/create.tsx",
      "parent": "/dashboard/_layout"
    },
    "/dashboard/_layout/coupon/create": {
      "filePath": "dashboard/_layout/coupon/create.tsx",
      "parent": "/dashboard/_layout"
    },
    "/dashboard/_layout/products/create": {
      "filePath": "dashboard/_layout/products/create.tsx",
      "parent": "/dashboard/_layout"
    },
    "/dashboard/_layout/category/": {
      "filePath": "dashboard/_layout/category/index.tsx",
      "parent": "/dashboard/_layout"
    },
    "/dashboard/_layout/coupon/": {
      "filePath": "dashboard/_layout/coupon/index.tsx",
      "parent": "/dashboard/_layout"
    },
    "/dashboard/_layout/order/": {
      "filePath": "dashboard/_layout/order/index.tsx",
      "parent": "/dashboard/_layout"
    },
    "/dashboard/_layout/products/": {
      "filePath": "dashboard/_layout/products/index.tsx",
      "parent": "/dashboard/_layout"
    },
    "/dashboard/_layout/users/": {
      "filePath": "dashboard/_layout/users/index.tsx",
      "parent": "/dashboard/_layout"
    },
    "/dashboard/_layout/category/$id/edit": {
      "filePath": "dashboard/_layout/category/$id.edit.tsx",
      "parent": "/dashboard/_layout"
    },
    "/dashboard/_layout/coupon/$id/edit": {
      "filePath": "dashboard/_layout/coupon/$id.edit.tsx",
      "parent": "/dashboard/_layout"
    },
    "/dashboard/_layout/products/$id/edit": {
      "filePath": "dashboard/_layout/products/$id.edit.tsx",
      "parent": "/dashboard/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
